# Generated by Django 4.1.3 on 2022-11-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('nombre', models.CharField(max_length=64)),
                ('descrip', models.CharField(blank=True, max_length=256, null=True)),
                ('direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('postal_id', models.IntegerField(blank=True, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('establecim', models.CharField(blank=True, max_length=64, null=True)),
                ('actividad', models.CharField(blank=True, max_length=32, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('tipodoc_id', models.IntegerField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, max_length=11, null=True)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('seg_retiro', models.IntegerField(blank=True, null=True)),
                ('corresp', models.IntegerField(blank=True, null=True)),
                ('reg_num', models.CharField(blank=True, max_length=16, null=True)),
                ('reg_categ', models.CharField(blank=True, max_length=16, null=True)),
                ('reg_juris', models.CharField(blank=True, max_length=16, null=True)),
                ('reg_venc', models.DateField(blank=True, null=True)),
                ('productor_id', models.IntegerField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=32, null=True)),
                ('banco_suc', models.CharField(blank=True, max_length=8, null=True)),
                ('banco_caja', models.CharField(blank=True, max_length=16, null=True)),
                ('banco_ctacte', models.CharField(blank=True, max_length=16, null=True)),
                ('debaut', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesMediosdepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('cliente_id', models.IntegerField()),
                ('mediodepago_id', models.IntegerField()),
                ('numero', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'clientes_mediosdepago',
                'managed': False,
            },
        ),
    ]
