# Generated by Django 4.1.3 on 2022-11-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': False, 'ordering': ('nombre',)},
        ),
    ]
