# Generated by Django 4.1.3 on 2023-01-27 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_alter_organizador_status_alter_provincias_status_and_more'),
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polizas',
            name='orden_id',
        ),
        migrations.AddField(
            model_name='polizas',
            name='tipopoliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametros.tipospoliza'),
        ),
        migrations.AlterField(
            model_name='clientesmediosdepago',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='polizas',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='productores',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
