# Generated by Django 4.1.3 on 2023-02-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_alter_organizador_status_alter_provincias_status_and_more'),
        ('actividad', '0002_remove_polizas_orden_id_polizas_tipopoliza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='tipopoliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tipospoliza'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
