# Generated by Django 4.1.3 on 2022-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_alter_clientes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('nombre', models.CharField(max_length=32)),
                ('razon_social', models.CharField(blank=True, max_length=64, null=True)),
                ('direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=32, null=True)),
                ('cuit', models.CharField(blank=True, max_length=13, null=True)),
                ('productor_id', models.IntegerField(blank=True, null=True)),
                ('comis_con_iva', models.IntegerField(blank=True, null=True)),
                ('ib_comis_prod', models.IntegerField(blank=True, null=True)),
                ('ib_comis_cobr', models.IntegerField(blank=True, null=True)),
                ('comis_cobranzas', models.IntegerField(blank=True, null=True)),
                ('dias_primer_cuota', models.IntegerField(blank=True, null=True)),
                ('liquidaciones', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('primer_cuota_iva', models.IntegerField(blank=True, null=True)),
                ('prop_iva', models.IntegerField(blank=True, null=True)),
                ('agente_iva', models.IntegerField(blank=True, null=True)),
                ('fecha_firma_convenio', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companias',
                'managed': False,
            },
        ),
    ]
