# Generated by Django 4.1.3 on 2023-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_ordenes_tipopoliza_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='fuente',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='zona_cza',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
