# Generated by Django 4.1.3 on 2022-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_companias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descrip', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField()),
                ('abrev', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'secciones',
                'managed': False,
            },
        ),
    ]
