# Generated by Django 4.1.3 on 2023-02-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0004_clientes_fuente_clientes_zona_cza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('nombre',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='coberturas',
            options={'verbose_name': 'cobertura', 'verbose_name_plural': 'coberturas'},
        ),
        migrations.AlterModelOptions(
            name='companias',
            options={'ordering': ('nombre',), 'verbose_name': 'compania', 'verbose_name_plural': 'companias'},
        ),
        migrations.AlterModelOptions(
            name='polizas',
            options={'verbose_name': 'poliza', 'verbose_name_plural': 'polizas'},
        ),
        migrations.AlterModelOptions(
            name='productores',
            options={'ordering': ('nombre',), 'verbose_name': 'productor', 'verbose_name_plural': 'productores'},
        ),
        migrations.AlterModelOptions(
            name='secciones',
            options={'ordering': ('nombre',), 'verbose_name': 'seccion', 'verbose_name_plural': 'secciones'},
        ),
        migrations.AddField(
            model_name='ordenes',
            name='localidad',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
