# Generated by Django 4.1.3 on 2022-11-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0004_secciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companias',
            options={'managed': False, 'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='secciones',
            options={'managed': False, 'ordering': ('nombre',)},
        ),
    ]
