# Generated by Django 4.1.3 on 2022-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0005_alter_companias_options_alter_secciones_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=64, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('org1_id', models.IntegerField(blank=True, null=True)),
                ('org2_id', models.IntegerField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=10, null=True)),
                ('ultima_orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productores',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
    ]
