# Generated by Django 4.1.3 on 2023-02-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0005_alter_clientes_options_alter_coberturas_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='status',
            new_name='activo',
        ),
    ]
