# Generated by Django 4.1.3 on 2023-02-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_banco_options_alter_bancosucu_options_and_more'),
        ('actividad', '0006_rename_status_clientes_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuota', models.IntegerField()),
                ('fecha_venc', models.DateField(blank=True, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('restante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rendicion_id', models.IntegerField()),
                ('nro_comprobante', models.CharField(max_length=8)),
                ('poliza_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametros.provincias', verbose_name='Poliza')),
            ],
            options={
                'db_table': 'cuotas_poliza',
            },
        ),
    ]
