# Generated by Django 4.1.3 on 2022-11-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0006_productores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiposdoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=5, null=True)),
                ('descrip', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'tiposdoc',
                'managed': False,
            },
        ),
    ]
