# Generated by Django 4.1.3 on 2023-01-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0007_tiposdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coberturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_collation='latin1_swedish_ci', max_length=64)),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'coberturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediosdepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=16)),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'mediosdepago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'monedas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, db_index=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('suma', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('prima', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('recargos', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('bonificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('premio', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('riesgo_desc', models.TextField(blank=True, null=True)),
                ('riesgo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('bien_asegurado', models.CharField(blank=True, max_length=80, null=True)),
                ('produccion', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('cobranza', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('recup_gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('nro_mediopago', models.CharField(blank=True, max_length=32, null=True)),
                ('responsable', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('num_poliza_ref', models.CharField(blank=True, max_length=32, null=True)),
                ('cod_productor', models.CharField(blank=True, max_length=16, null=True)),
                ('flag', models.CharField(blank=True, max_length=1, null=True)),
                ('codigo_productor', models.IntegerField(blank=True, null=True)),
                ('orden_productor', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipospedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Tipo de Pedido')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'tipospedido',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipospoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Tipo de Póliza')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'tipospoliza',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
    ]
