# Generated by Django 4.1.3 on 2023-02-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0008_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='cuota_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.cuotas', verbose_name='Cuotas'),
        ),
        migrations.CreateModel(
            name='rendiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compania_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.companias', verbose_name='Compañía')),
                ('productor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.productores', verbose_name='Productor')),
            ],
        ),
    ]
