# Generated by Django 4.1.3 on 2023-02-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0011_comprobantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='nro_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.comprobantes', verbose_name='Comprobante'),
        ),
    ]
