# Generated by Django 4.1.3 on 2023-02-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_banco_options_alter_bancosucu_options_and_more'),
        ('actividad', '0012_alter_cuotas_nro_comprobante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantes',
            options={'verbose_name': 'Comprobante', 'verbose_name_plural': 'Comprobantes'},
        ),
        migrations.AlterModelOptions(
            name='cuotas',
            options={'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos de cuotas'},
        ),
        migrations.AlterModelOptions(
            name='rendiciones',
            options={'verbose_name': 'Rendicion', 'verbose_name_plural': 'Rendiciones'},
        ),
        migrations.AlterModelOptions(
            name='tipos_comprobante',
            options={'verbose_name': 'Tipo de comprobante', 'verbose_name_plural': 'Tipos de comprobante'},
        ),
        migrations.AlterUniqueTogether(
            name='cuotas',
            unique_together={('poliza_id', 'nro_cuota')},
        ),
        migrations.AlterModelTable(
            name='comprobantes',
            table='comprobantes',
        ),
        migrations.AlterModelTable(
            name='rendiciones',
            table='rendiciones',
        ),
        migrations.AlterModelTable(
            name='tipos_comprobante',
            table='tipos_comprobantes',
        ),
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero', models.CharField(max_length=32)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('restante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('banco_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametros.banco', verbose_name='Banco')),
                ('cliente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.clientes', verbose_name='Cliente')),
                ('sucursal_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametros.bancosucu', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'cheque',
                'verbose_name_plural': 'cheques',
                'db_table': 'cheques',
            },
        ),
    ]
