# Generated by Django 4.1.3 on 2023-02-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0014_rename_rendicion_id_cuotas_rendicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='comprobante_id',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='cuota_id',
        ),
        migrations.AddField(
            model_name='pagos',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.comprobantes', verbose_name='Comprobante'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.cuotas', verbose_name='Cuota'),
        ),
    ]
