# Generated by Django 4.1.3 on 2023-02-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0015_remove_pagos_comprobante_id_remove_pagos_cuota_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheques',
            old_name='banco_id',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='cheques',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='cheques',
            old_name='sucursal_id',
            new_name='sucursal',
        ),
    ]
