# Generated by Django 4.1.3 on 2023-02-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_tipos_comprobante'),
        ('actividad', '0016_rename_banco_id_cheques_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantes',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='actividad.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='comprobantes',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametros.tipos_comprobante', verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Tipos_comprobante',
        ),
    ]
