# Generated by Django 4.1.3 on 2023-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0017_comprobantes_cliente_alter_comprobantes_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companias',
            name='productor',
        ),
        migrations.AddField(
            model_name='productores',
            name='companias',
            field=models.ManyToManyField(to='actividad.companias'),
        ),
    ]
