# Generated by Django 4.1.3 on 2023-03-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0018_remove_companias_productor_productores_companias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productores',
            name='org1_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productores',
            name='org2_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
