# Use root/mysql as user/password credentials

version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: prueba-web
    command: gunicorn asegurarse.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    hostname: web
  
  db:
    image: postgres:13.0-alpine
    volumes:
      # - ./asegurarse_init_db.sql:/docker-entrypoint-initdb.d/asegurarse_init_db_struct.sql
      # - ./asegurarse_init_db.sql:/docker-entrypoint-initdb.d/asegurarse_init_db_datos.sql
      - db_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=webtofly_db_user
      - POSTGRES_PASSWORD=bw1L[{wezRx9
      - POSTGRES_DB=webtofly_asegurarse


  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ivanberlot@gmail.com
      PGADMIN_DEFAULT_PASSWORD: i164iber
    volumes:
      - pgadmin-data:/var/lib/pgadmin

    hostname: adminer

volumes:
  db_volume:
  pgadmin-data: