# Generated by Django 4.1.3 on 2023-03-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosRubricados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha de la operación', null=True, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('Operaciones', 'Operaciones'), ('Rendiciones', 'Rendiciones')], max_length=16, verbose_name='Tipo')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'libro rubricado',
                'verbose_name_plural': 'libros rubricados',
                'db_table': 'libro_rubricados',
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='RegistrosLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero de orden')),
                ('fecha', models.DateField(blank=True, help_text='Fecha de registro de la poliza', null=True)),
                ('vigencia_desde', models.DateField(blank=True, help_text='Fecha de la vigencia desde de la poliza', null=True)),
                ('vigencia_hasta', models.DateField(blank=True, help_text='Fecha de la vigencia hasta de la poliza', null=True)),
                ('prima', models.DecimalField(decimal_places=2, help_text='Prima de la poliza', max_digits=11)),
                ('cliente_nombre', models.CharField(help_text='Nombre registrado del cliente', max_length=64)),
                ('cliente_direccion', models.CharField(help_text='Direccion del cliente', max_length=64)),
                ('compania_nombre', models.CharField(help_text='Nombre de la compañia', max_length=32)),
                ('orden_direccion', models.CharField(help_text='Direccion registrada de la orden. Ubicacion del riesgo', max_length=64)),
                ('riesgo_desc', models.CharField(help_text='Descripcion del riesgo de la orden. Bien a asegurar', max_length=64)),
                ('secciones', models.CharField(help_text='Nombre de la seccion de la orden. Riesgo a cubrir', max_length=64)),
                ('observaciones', models.CharField(max_length=64)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='reportes.librosrubricados')),
            ],
            options={
                'verbose_name': 'registro libro',
                'verbose_name_plural': 'registros libros',
                'db_table': 'registros_libros',
                'ordering': ('libro', 'fecha'),
            },
        ),
    ]
