# Generated by Django 4.1.3 on 2023-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librosrubricados',
            name='impresion',
            field=models.CharField(blank=True, choices=[('Encabezados', 'Imprimir Encabezados'), ('Rubricados', 'Imprimir Rubricados')], max_length=16, null=True, verbose_name='Impresión'),
        ),
    ]
