# Generated by Django 4.1.3 on 2023-03-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_librosrubricados_impresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='librosrubricados',
            name='fecha_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librosrubricados',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librosrubricados',
            name='pagina_desde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librosrubricados',
            name='pagina_hasta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
