# Generated by Django 4.1.3 on 2023-03-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_librosrubricados_fecha_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librosrubricados',
            name='generado',
            field=models.BooleanField(default=False),
        ),
    ]
