# Generated by Django 4.1.3 on 2023-03-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_librosrubricados_generado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroslibros',
            name='riesgo_desc',
            field=models.TextField(help_text='Descripcion del riesgo de la orden. Bien a asegurar'),
        ),
    ]
