# Generated by Django 4.1.3 on 2023-01-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'banco',
                'ordering': ('descrip',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bancosucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(blank=True, max_length=32, null=True)),
                ('codigo', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'bancosucu',
                'ordering': ('descrip',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediosdepago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Medio')),
                ('tipo', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Cuenta', 'Cuenta'), ('Otro', 'Otro')], max_length=16, verbose_name='Tipo')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'mediosdepago',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'monedas',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=4, verbose_name='CP')),
                ('cpa', models.CharField(max_length=16, verbose_name='CPA')),
                ('referencia', models.CharField(max_length=64, verbose_name='Referencia')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'postal',
                'ordering': ('referencia',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('orden', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipospedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Tipo de Pedido')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'tipospedido',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipospoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Tipo de Póliza')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'tipospoliza',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
    ]
