# Generated by Django 4.1.3 on 2023-01-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tiposdoc',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
