# Generated by Django 4.1.3 on 2023-02-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_tipos_comprobante'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipos_comprobante',
            table='tipos_comprobante',
        ),
    ]
